// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

// lang.js
export const SET_LOCALE = 'SET_LOCALE'



//Products
export const FETCH_PRODCUTS_SUCCESS = 'FETCH_PRODCUTS_SUCCESS'
export const FETCH_PRODCUTS_FAILURE = 'FETCH_PRODCUTS_FAILURE'
export const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS'

//Categories
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE'
export const UPDATE_CATEGORIES = 'UPDATE_CATEGORIES'